# Generated by Django 4.1.5 on 2023-03-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0007_remove_party_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='party.party')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='party.party')),
            ],
        ),
    ]
