branch-defaults:
  default:
    environment: ourcohol-dev
    group_suffix: null
environment-defaults:
  ourcohol-server-dev:
    branch: null
    repository: null
global:
  application_name: ourcohol
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
