branch-defaults:
  default:
    environment: OURcohol-env
    group_suffix: null
environment-defaults:
  OURcohol-eb-server-dev:
    branch: null
    repository: null
global:
  application_name: OURcohol-server
  branch: null
  default_ec2_keyname: hwanEC2_Key
  default_platform: Python 3.9
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
