# Generated by Django 4.1.5 on 2023-03-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_user_active_party"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="active_party",
            field=models.IntegerField(default=0),
        ),
    ]
