# Generated by Django 4.1.5 on 2023-03-24 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_alter_user_active_party"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="active_party",
        ),
    ]
