# Generated by Django 4.1.5 on 2023-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_remove_user_active_party"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="amount_alcohol",
            field=models.FloatField(default=60.84),
        ),
    ]
