# Generated by Django 4.1.5 on 2023-04-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_user_amount_alcohol"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type_alcohol",
            field=models.CharField(default="soju", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="amount_alcohol",
            field=models.FloatField(default=1),
        ),
    ]
