# Generated by Django 3.2.9 on 2023-05-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20230518_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_memory',
            field=models.CharField(blank=True, default='', max_length=4294967295, null=True),
        ),
    ]
