# Generated by Django 3.2.9 on 2023-05-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_memory',
            field=models.TextField(blank=True),
        ),
    ]
