# Generated by Django 3.2.9 on 2023-05-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_user_image_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_memory',
        ),
    ]
