# Generated by Django 4.1.5 on 2023-02-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
