# Generated by Django 4.1.5 on 2023-02-27 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0002_alter_party_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='king_user_id',
            field=models.ManyToManyField(blank=True, related_name='win_party', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='last_user_id',
            field=models.ManyToManyField(blank=True, related_name='lose_party', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='participations',
            field=models.ManyToManyField(related_name='participate', to=settings.AUTH_USER_MODEL),
        ),
    ]
