# Generated by Django 4.1.5 on 2023-03-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_participant_is_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
