# Generated by Django 4.1.5 on 2023-03-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_alter_party_ended_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='is_delete',
        ),
    ]
