# Generated by Django 4.1.5 on 2023-03-23 04:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("party", "0007_remove_party_is_delete"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
