# Generated by Django 4.1.5 on 2023-03-27 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("party", "0008_delete_participant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="party",
            name="is_active",
        ),
    ]
