# Generated by Django 4.1.5 on 2023-03-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("party", "0009_remove_party_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
