# Generated by Django 4.1.5 on 2023-03-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("party", "0010_party_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
