# Generated by Django 4.1.5 on 2023-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("party", "0013_remove_party_is_active_alter_party_ended_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
