# Generated by Django 4.1.5 on 2023-03-23 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("party", "0008_delete_participant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("drank_beer", models.IntegerField(default=0)),
                ("drank_soju", models.IntegerField(default=0)),
                ("amount_alcohol", models.IntegerField(default=1)),
                ("is_host", models.BooleanField(default=False)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="party.party",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connected_party",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
