# Generated by Django 4.1.5 on 2023-04-08 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("participant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="amount_alcohol",
        ),
    ]
